name: bhbot-environment

dependencies:
    - pip
    - altgraph
    - appdirs
    - asttokens
    - attrs
    - auto-py-to-exe
    - backcall
    - beautifulsoup4
    - bleach
    - bottle
    - bottle-websocket
    - bsdiff4
    - certifi
    - cffi
    - chardet
    - charset-normalizer
    - colorama
    - decorator
    - defusedxml
    - Deprecated
    - docopt
    - dsdev-utils
    - Eel
    - executing
    - fastjsonschema
    - fonttools
    - future
    - gevent
    - gevent-websocket
    - greenlet
    - idna
    - jedi
    - Jinja2
    - jsonschema
    - jsonschema-specifications
    - jupyter_client
    - jupyter_core
    - jupyterlab_pygments
    - keyboard
    - MarkupSafe
    - matplotlib-inline
    - mistune
    - nbclient
    - nbconvert
    - nbformat
    - packaging
    - pandocfilters
    - parso
    - pbr
    - pefile
    - pickleshare
    - pillow
    - pipreqs
    - platformdirs
    - prompt-toolkit
    - psutil
    - pure-eval
    - pyasn1
    - pycparser
    - Pygments
    - pyinstaller
    - pyinstaller-hooks-contrib
    - PyNaCl
    - pyparsing
    - pypiwin32
    - PySimpleGUI
    - python-dateutil
    - PyUpdater
    - pywin32
    - pywin32-ctypes
    - pyzmq
    - referencing
    - regex
    - requests
    - rpds-py
    - rsa
    - setuptools
    - six
    - soupsieve
    - stack-data
    - tinycss2
    - tornado
    - traitlets
    - wakepy
    - wcwidth
    - webencodings
    - wheel
    - whichcraft
    - wrapt
    - yarg
    - zope.event
    - zope.interface
