name: ActionLint
on:
  push: 

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:       
    - uses: actions/checkout@v3
    - uses: devops-actions/actionlint@48ca80d7da4ffd5ed31b7981702bc6bb4b242c63 #v0.1.2
      continue-on-error: true
      id: action-lint
