name: black-action
on: [push, pull_request]
jobs:
  linter_name:
    name: runner / black formatter
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: datadog/action-py-black-formatter@v2.1
        with:
          check_mode: "true"
