name: Workflow for Codecov example-python
on: [push, pull_request]
permissions:
  contents: read

jobs:
  run:
    runs-on: self-ubuntu
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
      - name: Install pytest
        run: pip install pytest-cov
      - name: Run tests and collect coverage
        run: pytest --cov app ${{ env.CODECOV_ATS_TESTS }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@125fc84a9a348dbcf27191600683ec096ec9021c # v4.4.1
        with:
          flags: smart-tests
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
