name: FileDiff
on:
  pull_request:
permissions:
  contents: read

jobs:
  filediff:
    name: filediff
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - name: Checkout default branch
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Create filediff comment
        uses: Shopify/filediff@a662df8303d1056aa3561b5524610ae65b63fc78 # main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          pre_diff_script: npm run build
          target_branch: main
          dir_glob: packages/**/dist/**,images/**
          file_details_open: true
